version: 2

build:
  image: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

python:
  version: "3.8"
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .

# Don't build any extra formats
formats: []
